# Generated by Django 5.2.7 on 2025-11-29 17:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesoriu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_accesoriu', models.CharField(max_length=255)),
                ('pret_accesoriu', models.FloatField()),
                ('stoc_accesoriu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategorieMasina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('icon_categorie', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
                ('nr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_marca', models.CharField(max_length=255, unique=True)),
                ('tara_origine', models.CharField(max_length=255)),
                ('an_infiintare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serviciu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_serviciu', models.CharField(max_length=255)),
                ('pret_serviciu', models.FloatField()),
                ('descriere_serviciu', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('tara', models.CharField(blank=True, max_length=100)),
                ('judet', models.CharField(blank=True, max_length=100)),
                ('oras', models.CharField(blank=True, max_length=100)),
                ('strada', models.CharField(blank=True, max_length=100)),
                ('cod_postal', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret_masina', models.FloatField()),
                ('in_stoc', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=100)),
                ('an_fabricatie', models.IntegerField()),
                ('kilometraj', models.IntegerField(default=0)),
                ('tip_combustibil', models.CharField(choices=[('BENZINA', 'Benzină'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HIBRID', 'Hibrid'), ('GPL', 'GPL'), ('ALTUL', 'Altul')], default='BENZINA', max_length=100)),
                ('data_adaugarii', models.DateField(auto_now_add=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='imagini_masini/')),
                ('accesorii', models.ManyToManyField(blank=True, to='aplicatie_masini.accesoriu')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_masini.categoriemasina')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_masini.marca')),
                ('servicii', models.ManyToManyField(blank=True, to='aplicatie_masini.serviciu')),
            ],
        ),
    ]
