# Generated by Django 5.2.7 on 2025-10-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesoriu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_accesoriu', models.CharField(max_length=255)),
                ('pret_accesoriu', models.FloatField()),
                ('stoc_accesoriu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategorieMasina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_marca', models.CharField(max_length=255, unique=True)),
                ('tara_origine', models.CharField(max_length=255)),
                ('an_infiintare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serviciu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_serviciu', models.CharField(max_length=255)),
                ('pret_serviciu', models.FloatField()),
                ('descriere_serviciu', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='locatie',
            name='nr',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret_masina', models.FloatField()),
                ('in_stoc', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=100)),
                ('an_fabricatie', models.IntegerField()),
                ('kilometraj', models.IntegerField(default=0)),
                ('tip_combustibil', models.CharField(choices=[('BENZINA', 'Benzină'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HIBRID', 'Hibrid'), ('GPL', 'GPL'), ('ALTUL', 'Altul')], default='BENZINA', max_length=100)),
                ('data_adaugarii', models.DateField(auto_now_add=True)),
                ('accesorii', models.ManyToManyField(blank=True, to='aplicatie_masini.accesoriu')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_masini.categoriemasina')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_masini.marca')),
                ('servicii', models.ManyToManyField(blank=True, to='aplicatie_masini.serviciu')),
            ],
        ),
    ]
