# Generated by Django 5.2.7 on 2025-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0002_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncercareLogare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_folosit', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_folosit', models.CharField(max_length=100)),
                ('data_incercare', models.DateTimeField()),
            ],
        ),
    ]
