# Generated by Django 5.2.7 on 2025-11-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0002_accesoriu_categoriemasina_marca_serviciu_locatie_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masina',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='imagini_masini/'),
        ),
    ]
