# Generated by Django 5.2.7 on 2025-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0003_masina_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriemasina',
            name='icon_categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
