# Generated by Django 5.2.7 on 2025-12-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0003_incercarelogare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incercarelogare',
            name='data_incercare',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
