# Generated by Django 5.2.7 on 2025-12-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0004_alter_incercarelogare_data_incercare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizare_zona_admin', 'Poate vedea log-uri si info server')]},
        ),
    ]
