# Generated by Django 5.2.7 on 2025-12-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizare_zona_admin', 'Poate vedea log-uri si info server'), ('vizualizare_oferta', 'Poate vizualiza pagina cu oferte')]},
        ),
    ]
