# Generated by Django 5.2.7 on 2025-12-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0007_customuser_blocat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizare_zona_admin', 'Poate vedea log-uri si info server'), ('vizualizare_oferta', 'Poate vizualiza pagina cu oferte'), ('blocheaza_utilizator', 'Poate bloca/debloca utilizatori')]},
        ),
    ]
