# Generated by Django 5.2.7 on 2026-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masina',
            name='in_stoc',
        ),
        migrations.AddField(
            model_name='masina',
            name='stoc',
            field=models.IntegerField(default=1, verbose_name='Stoc disponibil'),
        ),
    ]
