# Generated by Django 5.2.7 on 2026-02-28 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_masini', '0009_remove_masina_in_stoc_masina_stoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('pret_total', models.FloatField(default=0)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comenzi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comenzi',
                'ordering': ['-data_comanda'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=1)),
                ('pret_unitar', models.FloatField()),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_masini.comanda')),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_masini.masina')),
            ],
            options={
                'verbose_name_plural': 'Iteme Comenzi',
            },
        ),
    ]
